# Generated by Django 5.2.17 on 2026-08-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Health Categories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='conditions/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='catalogue.healthcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('composition', models.TextField(blank=True)),
                ('form', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('uses', models.TextField(blank=True)),
                ('how_it_works', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('storage', models.TextField(blank=True)),
                ('also_known_as', models.CharField(blank=True, max_length=255)),
                ('pack_size', models.CharField(blank=True, max_length=100)),
                ('prescription_required', models.BooleanField(default=False)),
                ('drug_type', models.CharField(blank=True, max_length=100)),
                ('habit_forming', models.BooleanField(default=False)),
                ('pregnancy_category', models.CharField(blank=True, max_length=50)),
                ('alcohol_interaction', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='all_medicines', to='catalogue.healthcategory')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_medicines', to='catalogue.healthcategory')),
                ('conditions', models.ManyToManyField(blank=True, related_name='all_medicines', to='catalogue.healthcondition')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='catalogue.manufacturer')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_medicines', to='catalogue.healthcondition')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medicines/')),
                ('is_primary', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.medicine')),
            ],
        ),
    ]
