# Generated by Django 5.2.17 on 2026-09-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_healthcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='active_ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicine',
            name='inactive_ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='interactions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='last_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='route',
            field=models.CharField(blank=True, default='Oral', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='serious_side_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='source_name',
            field=models.CharField(blank=True, default='FDA / DailyMed / NLM', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='source_url',
            field=models.URLField(blank=True, default='https://dailymed.nlm.nih.gov/', max_length=500),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
