# Generated by Django 5.2.17 on 2026-09-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_medicine_active_ingredients_medicine_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_image_assets', to='catalogue.medicine'),
        ),
    ]
